### ISSUE TITLE
segment ends of elevated roundabouts posses half elevated half ground charactristics.

### ISSUE THREAD

**Issue by kianzarrin** [Strdate/AutomaticRoundaboutBuilder#10]
see https://github.com/kianzarrin/myrepo/issues/6#issuecomment-586166355

**Comment by Strdate** [comment]
Interesting issue!

**Comment by kianzarrin** [comment]
`NetNode,m_elevation` is currently 0 for elevated roads. we should set to it correct number.

**Comment by kianzarrin** [comment]
OK fixed it.
![Screenshot (709)](https://user-images.githubusercontent.com/26344691/77219781-9bd9a600-6b41-11ea-9986-e13f6ce6b6f8.png)
![Screenshot (708)](https://user-images.githubusercontent.com/26344691/77219783-9f6d2d00-6b41-11ea-871c-804ea4bc79d3.png)

**Comment by Strdate** [comment]
Thank you very much for your care! It is now released

**Comment by kianzarrin** [comment]
Vow that was fast release.
