### ISSUE TITLE
Better elevation shortcuts

### ISSUE THREAD

**Issue by kianzarrin** [Strdate/AutomaticRoundaboutBuilder#12]
I tried to contact you with Discord but I got no response. I don't know if you read your Discord. ‏if you like I can set homepage to set elevation to 0 also elevation step can be read from net tool

**Comment by Strdate** [comment]
Hi, I unfortunately don't read discord very often and my presence on github isn't often much better. I appreciate anything that improves the experience, so you can definitely create a merge request and I will merge it.
Thanks for your support!

**Comment by Strdate** [comment]
Done
