### ISSUE TITLE
improve Roundabout tool toggle enable/dissable

### ISSUE THREAD

**Issue by kianzarrin** [Strdate/AutomaticRoundaboutBuilder#16]
When I want to build roundabout I open the roundabout panel. If I have forgotten to select the road then I select a road from Road Tool rather than the drop box because its easier to find that way.

At this point I press Control+O to refocus roundabout builder but instead roundabout window disappears.

I could click on the roundabout window but I have to remember to avoid all the UI elements in there so it requires a bit of focus. its easier to just press control+o

When Roundabout window is out of focus, pressing ctrl+o clicking the roundabout button should refocus the window.

**Comment by Strdate** [comment]
Could be, but it maybe would be confusing for the players who have learned to use it this way? Probably better option would be not to drop focus at all, but that most certainly requires patching, which I was able to avoid so far

**Comment by kianzarrin** [comment]
maybe introduce an option. although that might make the option tab messy.

Why would anyone put the Roundabout tool out of focus and then press ctrl+O?

**Comment by Strdate** [comment]
I meant that they might be used to double-press, which is a possibility how to regain focus

**Comment by Strdate** [comment]
I was thinking about this. Eventually I decided to implement it as you suggested
