### ISSUE TITLE
Allow setting TMPE can enter blocked junction only for vehicles already at the roundabout

### ISSUE THREAD

**Issue by brunoais** [Strdate/AutomaticRoundaboutBuilder#2]
Currently, at the TMPE integration, if the option to allow vehicles in blocked junction is active, it sets both options as active, both the one entering the roundabout and the one staying at the roundabout.
I'd like to be able to configure the TMPE integration so that only the cars already at the roundabout can continue at the junction.

As for how to find which nodes, I can give a non-promised possible solution:
1. You can get which side of the road the cars run for the map (TMPE uses this API also).
2. You apply the priority only to the segment that is continued from the joint road.

E.g. for 2: If it is right-side traffic (as in most EU), if the road joins from the right, then it is calculated as an entrance and wouldn't get the "allow vehicles in blocked junction" active.

Is this viable for the extension?

**Comment by Strdate** [comment]
I added this option in the latest version (1.5.1) 10 days ago. Check it out and tell me if it's working to you. In tmpe settings there are now two separate checkboxes for main roads and connecting roads.

**Comment by brunoais** [comment]
I see... I confirm the version I have was not updated. I'll make sure to have it up to date and then I'll feedback here.
Expect feedback over the weekend, though. No time to open the game again until then.

**Comment by brunoais** [comment]
The option is there and works as you mentioned. Sorry about that.

**Comment by Strdate** [comment]
It is ok! Thank you for being interested in improving the mod :)
