### ISSUE TITLE
TM:PE options screen update

### ISSUE THREAD

**Issue by originalfoo** [Strdate/AutomaticRoundaboutBuilder#21]
I don't think this will affect your mod on cursory glance of the code, but wanted to check just in case.

The TM:PE mod options screens are about to get heavily refactored, including significant changes to UI components, class structure, etc. If this affects your mod please let me know and we'll delay those updates until a robust solution can be found (a PR for a mod options API is already in review). A summary of the changes can be found in https://github.com/CitiesSkylinesMods/TMPE/issues/1356

The TM:PE toolbar, ModUI and other stuff is unaffected by these changes.

> BTW, krzychu has been working on some vast improvements to how traffic flows at junctions which should greatly improve effectiveness of the policies your mod sets at roundabouts - see vids from this comment onwards: https://github.com/CitiesSkylinesMods/TMPE/issues/1229#issuecomment-1030912846 :)

**Comment by Strdate** [comment]
The worst thing that should happen is that the integrated actions in roundabout builder will stop working, so go on.
All calls to TMPE from roundabout builder are concentrated here https://github.com/Strdate/AutomaticRoundaboutBuilder/blob/master/RoundaboutBuilder/GameActions/TmpeActions.cs

**Comment by originalfoo** [comment]
Yeah, those things you're accessing don't have any planned changes that I'm aware of. When I first looked at that code I thought `TmpeSetupPanel` might be referring to the actual TMPE mod options UI, but it's referring to a panel in Roundabout Builder. So hopefully this update to TMPE mod options won't affect any part of your mod; still we'll try and push it to TEST workshop page first and do some extra testing just to be sure.
