### ISSUE TITLE
Automatic Undo or Oh-Sh* button to undo if roundabout creation failed

### ISSUE THREAD

**Issue by kvakvs** [Strdate/AutomaticRoundaboutBuilder#3]
Sometimes creating a roundabout fails.
Undo automatically, or allow the user to restore the previous state of the road network.

**Comment by Strdate** [comment]
This needs significant changes to the code, so until I make a complete mod overhaul I won't probably add this. Anyway, it is a feature requested for a long time and I have it on my mind.

**Comment by Strdate** [comment]
There is undo now, closing
