### ISSUE TITLE
Feature request: Resize roundabout with mouse wheel and modifier button

### ISSUE THREAD

**Issue by turb0mint** [Strdate/AutomaticRoundaboutBuilder#7]
Can we add a binding to allow the roundabout to be resized after selecting of the intersection with the mouse wheel and a modifier key?

**Comment by Strdate** [comment]
Sounds like a cool idea. I will look at it.

**Comment by Strdate** [comment]
There is a problem: Mouse wheel is bound to camera zoom by default, no matter if any modifier key is pressed...

**Comment by Strdate** [comment]
For now closing
