### ISSUE TITLE
remove nodes too close to roundabout

### ISSUE THREAD

**Issue by kianzarrin** [Strdate/AutomaticRoundaboutBuilder#8]
As you can see from the pictures bellow the round about builder creates nodes that are too close to the round about:
![Screenshot (33)](https://user-images.githubusercontent.com/26344691/68601834-d3f31d00-04ad-11ea-9294-a3f7f21158db.png)
![Screenshot (31)](https://user-images.githubusercontent.com/26344691/68601835-d48bb380-04ad-11ea-8ab4-925263136f5b.png)

[this code](https://github.com/Strdate/AutomaticRoundaboutBuilder/blob/master/RoundaboutBuilder/Tools/EdgeIntersections2.cs#L218)  prevents nodes from touching the roundabout:
```if (VectorDistance(bezier2.a, bezier2.d) < MIN_BEZIER_LENGTH)```

`MIN_BEZIER` is defined [here](https://github.com/Strdate/AutomaticRoundaboutBuilder/blob/2c9de24d8e53376fe4ee942e390a03ca4c37b700/RoundaboutBuilder/Tools/EdgeIntersections2.cs#L21):
```public static readonly int MIN_BEZIER_LENGTH = 10;```

Even so the nodes Are still too close. This causes several problems:
1- steep slope: if there is elevation, tiny segments near the round about will have sharp slope.
2- traffic jams: I fix peoples cities and I face this problem a lot. Cars lane switch way to close to the round about jamming the traffic. [in this issue](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/539) I have tried to fix this on TMPE side. but perhaps its better to fix it here to avoid the problem to exist in the first place.

~I suggest to increase `MIN_BEZIER_LENGTH` to `40(5 units)`.~
edit: I take it back I tried it and it didn't work. maybe it make things even worse.
EDIT2: Updating MIN_BEZIER_LENGTH does work.

**Comment by kianzarrin** [comment]
I will play around with MIN_BEZIER_LENGTH to see what happens.

**Comment by kianzarrin** [comment]
changing MIN_BAZIER to 80 didn't fix the problem: 
![Screenshot (43)](https://user-images.githubusercontent.com/26344691/68605100-83cb8900-04b4-11ea-8926-5e6f87faa592.png)

But it might have made it worse:
![Screenshot (44)](https://user-images.githubusercontent.com/26344691/68605102-84641f80-04b4-11ea-90b4-4dcb5cb275df.png)

I need to take deep dive into the code!

**Comment by Strdate** [comment]
Unfortunately there are still bugs that I didn't track down.
- Sometimes the mod fails to connect one of the roads to the roundabout
- Sometimes the algorithm that should remove the close nodes fails it job and does nothing

It is possible that for some players the repair-short-segment algorithm fails every time. Unfortunately I can't reproduce that. (the method returns false or whatever)

I rewrote that algorithm several times, the last time I found a severe bug there was two weeks ago. See the [commit](https://github.com/Strdate/AutomaticRoundaboutBuilder/commit/2c9de24d8e53376fe4ee942e390a03ca4c37b700)

If you want to really understand the code, you can start with one of the oldest commit. The core is still the same so it might be easier to understand. Feel free to ask me anything. It is nice to see you interested :)

With today's update I increased MIN_BEZIER_LENGTH to 16. But again, the low number might not be the cause of the problems.

Do you have debugger attached? Without it finding bugs is almost impossible: 
[Attaching debugger to Cities:Skylines](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Attaching-Debugger-to-Cities-Skylines)

**Comment by kianzarrin** [comment]
@Strdate 
>With today's update I increased MIN_BEZIER_LENGTH to 16

~~I hope this was not because of something I said because as I explained above and despite my original guess increasing MIN_BEZIER_LENGTH did not solve the problem at all. I am NOT sure but it may make things worse.~~

EDIT: It seems to work. I just did not realize the new dll is not loaded.

**Comment by kianzarrin** [comment]
I started to work on this. Sorry to take my sweet time I was preoccupied by TMPE.

I think we can start off like this:
```C#
public List<ushort> TouchingNodes { get; private set; } = new List<ushort>();

if ( !Ellipse.IsInsideEllipse(newNetNode.m_position))
{
    OuterNodes.Add(newNode);
    OuterSegments.Add(segment);

    //ADDED CODE:
    ushort MIN_OUTER_SEGMENT_LEN = 5 * 8; //5 units * 8 meters per unit
    NetSegment netSegment = GetSegment(segment);
    if (netSegment.m_averageLength < MIN_OUTER_SEGMENT_LEN )
    {
        TinyOuterSegments.Add(segment);
        TouchingNodes.Add(netSegment.GetOtherNode(node));
    }
}
else
{
    InnerNodes.Add(newNode);
    InnerSegments.Add(segment);
    DFS(newNode);
}
```

EDIT: or maybe I can avoid extra lists and parse the list of outer segments later.

**Comment by kianzarrin** [comment]
@Strdate I made a mistake because I did not realize I am not loading new dll when I rebuild.
increasing MIN_BEZIER_LENGTH does work :) The question is what should be the value? I suggest 30 to 40(4 to 5 units). 

Adding post processing also might be a good idea to smooth out the slopes. We may even call the electrix tools to do that.

**Comment by Strdate** [comment]
Ok, I will try increasing it in the next update. Now it is 16
